name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./main/1.robot_cleaner_move_rotate.cpp
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
