name: ROS Catkin CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-ros-core  # You can use melodic, humble, etc.

    steps:
      - uses: actions/checkout@v4

      - name: Setup ROS environment
        run: |
          source /opt/ros/noetic/setup.bash
          apt-get update
          apt-get install -y python3-catkin-tools build-essential

      - name: Build ROS package
        run: |
          source /opt/ros/noetic/setup.bash
          cd $GITHUB_WORKSPACE
          catkin_make

      - name: Run tests
        run: |
          source devel/setup.bash
          rostest your_package_name test_file.test  # optional if you have tests
