name: ROS Catkin Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-ros-core

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install catkin and tools
        run: |
          apt-get update
          apt-get install -y ros-noetic-catkin python3-catkin-tools build-essential

      - name: Build with catkin_make
        run: |
          source /opt/ros/noetic/setup.bash
          cd $GITHUB_WORKSPACE
          catkin_make

      - name: Run tests
        run: |
          source devel/setup.bash
          rostest your_package_name your_test_file.test
